name: Generate Snake

on:
  schedule:
    # Se ejecuta cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout (obtener el código)
      - uses: actions/checkout@v4 

      # Usa la versión v3 sin el subdirectorio /svg
      - uses: Platane/snk@v3
        id: snake-svg
        with:
          github_user_name: robertskrr
          # Genera los archivos en el directorio temporal 'dist'
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # 3. Publica los cambios a la rama 'output'
      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v4 
        with:
          target_branch: output # Rama de destino
          build_dir: dist       # Directorio con los archivos generados
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
